### PR TITLE
Fix dockerfile

### LINKED ISSUE #4: Dockefile fails to build in tekton
The Dockefile needs to be a multi-stage to do the build and then copy the jar in second stage.

To reproduce
```
git clone https://github.com/ibm-garage-cloud/template-java-spring
cd template-java-spring
docker build . -f Dockerfile
```
You will see an error like this
```
Complete!
Removing intermediate container be7c42ff4f48
 ---> f3263e864eb7
Step 3/5 : COPY ./build/libs/*.jar ./server.jar
COPY failed: no source files were specified
```

### PR DESCRIPTION
**Pull request by csantanapr**
Fixes #4 #6

### CODE REVIEW

**Comment by csantanapr** [comment]
Error
```
[package : deploy] + echo 'CHECKING CHART (lint)'
[package : deploy] + helm lint ./chart/template-java-spring
[package : deploy] ==> Linting ./chart/template-java-spring
[package : deploy] [ERROR] Chart.yaml: directory name (template-java-spring) and chart name (template-spring-boot) must be the same
[package : deploy] [INFO] Chart.yaml: icon is recommended
```

**Comment by csantanapr** [comment]
🎉 Got tekton to work on java too
```
NAME                             STARTED          DURATION     STATUS                       
igc-java-gradle-run-w2kbr        7 minutes ago    6 minutes    Succeeded
```

**Comment by mjperrins** [comment]
Can you check this Dockerfile changes work find for a build in Jenkins for IKS ? one of the objectives is to keep the Dockerfile identical between the two. @seansund has added Buildah for the Jenkins approach can we sync on this ?

**Comment by csantanapr** [comment]
I check that Dockerfile works with IBM Container registry with IKS and OCP from jenkins or tekton

```
[build : build] BUILDING CONTAINER IMAGE: us.icr.io/catalyst-demos/template-java-spring:1.0.0-5f592bf
[build : build] + echo -e 'BUILDING CONTAINER IMAGE: us.icr.io/catalyst-demos/template-java-spring:1.0.0-5f592bf'
[build : build] + ibmcloud cr image-tag us.icr.io/catalyst-demos/template-java-spring:1.0.0 us.icr.io/catalyst-demos/template-java-spring:1.0.0-5f592bf
[build : build] Creating new tag 'us.icr.io/catalyst-demos/template-java-spring:1.0.0-5f592bf' that refers to 'us.icr.io/catalyst-demos/template-java-spring:1.0.0'
[build : build] 
[build : build] OK
[build : build] Available images in registry
[build : build] + echo -e 'Available images in registry'
[build : build] + ibmcloud cr images --restrict catalyst-demos/template-java-spring
[build : build] Listing images...
[build : build] 
[build : build] REPOSITORY                                      TAG             DIGEST         NAMESPACE        CREATED         SIZE     SECURITY STATUS   
[build : build] us.icr.io/catalyst-demos/template-java-spring   1.0.0           2fe44fc1537c   catalyst-demos   9 seconds ago   213 MB   Scanning...   
[build : build] us.icr.io/catalyst-demos/template-java-spring   1.0.0-5f592bf   2fe44fc1537c   catalyst-demos   9 seconds ago   213 MB   Scanning...   
[build : build] 
[build : build] OK
```

**Pull request merged**
