### PR TITLE
Enabling appsody

### PR DESCRIPTION
**Pull request by Hemankita**

### CODE REVIEW

**Comment by Hemankita** [comment]
Need to fix java-dashmetrics - WIP

**Comment by seansund** [comment]
Why maven and not Gradle?

**Comment by mjperrins** [comment]
Lets keep this Starter Kit with a single build dependency manager ie. Gradle, lets not mix them both causes more confusion for a developer

**Comment by csantanapr** [comment]
There is no appsody stack that handles gradle only maven. 

We want to have a template app that we can take over with appsody, show the developer how to benefit from appsody for example not having any tools or java installed, and just do appsody run locally and then have a tekton pipeline to deploy

**Comment by csantanapr** [comment]
If you folks really don’t like this approach to have it working with gradle or maven what other atternstives you propose?

1. Remove gradle and replace with maven
2. Create duplicate repo for template that uses maven and compatible with the appsody spring boot stack

**Comment by mjperrins** [comment]
@seansund so whats the issue with going to Maven to keep the core the same ? I know the Java people have preference, I know Gradle is better and from Google, if we switch over what is the impact ? seems a little short sighted of product engineering not to support the tools real Java developers use ? Spring Boot, not Liberty and Grade at the tools in the enterprise, is it better to have a separate template ?

**Comment by mjperrins** [comment]
That's the conclusion I am at, lets let @seansund make the decision being the hard core Java developer , I suspect separate until Apsody support Gradle then merge , that way the Spring Boot + Grady pattern is retained which is closer to Enterprise developers use of Java

**Pull request merged**
